# Site settings
title: Batuhan Sevinc
description: Personal Website
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Batuhan Sevinc
user_description: Fresh graduated Software Engineer. Unity Game Developer, Software Engineer with 4+ years of experience. Currently working on game development (Casual, Hyper Casual, Hybrid Casual, Idle, Arcade).
user_title: Software Engineer
email: eyupbatuhansevinc@gmail.com
twitter_username: bthnsvnc
instagram_username: bthnsvnc
#facebook_username: mauricio.urraco
linkedin_username: eyupbatuhansevinc
github_username:  batuhansevinc
# medium_username: lorem_ipsum
# medium_url: lorem_ipsum.medium.com
# gplus_username:  lorem_ipsum

exclude: ['package.json', 'src' , 'node_modules']
