# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|batuhansevinc.github.io| "https://github.com/#{batuhansevinc.github.io}" }

# gem "rails"

gem "jekyll", "~> 4.1"

group :jekyll_plugins do
    gem 'jekyll-sitemap'
    gem 'jekyll-feed'
    gem 'jekyll-seo-tag'
end